server:
  port: 8989

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:mem:practice_db
    username: sa
    password: 123456
    driverClassName: org.h2.Driver
