server:
  port: 8702

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  datasource:
    url: jdbc:h2:mem:organizations
    username: sa
    password: 123456
    driverClassName: org.h2.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8700/uaa/token_keys
