server:
  port: 8701

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          organization-ui:
            provider: uaa
            client-id: organization-ui
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,organization,department
          organization-read:
            client-id: organization-read
            provider: uaa
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri-template: "{baseUrl}/organization/read"
            scope: organization.read
          organization-edit:
            provider: uaa
            client-id: organization-edit
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri-template: "{baseUrl}/organization/edit"
            scope: organization.edit
        provider:
          uaa:
            authorization-uri: http://localhost:8700/uaa/oauth/authorize
            token-uri: http://localhost:8700/uaa/oauth/token
            user-info-uri: http://localhost:8700/uaa/userinfo
            user-name-attribute: sub
            jwk-set-uri: http://localhost:8700/uaa/token_keys
