server:
  port: 8703

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  datasource:
    url: jdbc:h2:mem:departmants
    username: sa
    password: 123456
    driverClassName: org.h2.Driver